apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs-volume
  labels:
    type: nfs
spec:
  storageClassName: nfs-storageclass
  claimRef:
    name: postgres-persistent-nfs-volume-claim
    namespace: default
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/var/nfsshare/pgdata"
    server: 10.0.2.7
