apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-nfs-volume-claim
spec:
  storageClassName: nfs-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
